; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.1.8 on Mon Nov 23 2020 08:08:51 GMT-0800 (Pacific Standard Time)
M561 ; clear any bed transform
G29  ; probe the bed and enable compensation


