; pause.g
; called when a print from SD card is paused
;
; generated by RepRapFirmware Configuration Tool v3.1.8 on Mon Nov 23 2020 08:08:53 GMT-0800 (Pacific Standard Time)
M83            ; relative extruder moves
G91            ; relative positioning
G1 Z50 F360    ; lift Z by 50mm
G90            ; absolute positioning


